import React from "react";
import { useRouter } from "next/router";
import { useQuery } from "@apollo/client";
import { LoadArtists } from "../../graphql/queries";
import Head from "next/head";
import AlbumList from "../../components/albumList";

const ArtistPage = () => {
  const routes = useRouter();
  const { id } = routes.query;
  const { data, loading, error } = useQuery(LoadArtists);

    if (loading) return <div>Loading...</div>;
    if (error) return  <div>Failed to to fetch data...</div>;

  const artiest = data.queryArtists.find((artist) => artist.id === id);

  return (
    <div>
      <Head>
        <title>{artiest.name} Albums</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 data-testid="header-title">{artiest.name} Albums</h1>
        <div className="mt-3" data-testid="album-list">
          {artiest && <AlbumList  albums={artiest.albums} />}
        </div>
      </main>
    </div>
  );
};

export default ArtistPage;
