import Head from "next/head";
import Image from 'next/image'
import { useQuery } from "@apollo/client";
import { LoadArtists } from "../graphql/queries";

import ArtistsList from "../components/artistsList";

export default function Home() {
  const { loading, error, data } = useQuery(LoadArtists);

  if (loading) return <div>Loading...</div>;
  if (error) return  <div>Filed to to fetch data...</div>

  return (
    <>
      <Head>
        <title>Spotify GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Image src={'/spotify-banner.png'} alt={'Spotify Banner'}
          width={800} height={300} />
          <div className="mt-4" data-testid="artists-list">
              { data && <ArtistsList  artists={data.queryArtists} />}
          </div>
      </main>
    </>
  );
}
